name: Typecheck

on:
  pull_request:
  push:
    branches: [master]

jobs:
  typecheck:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Use Node.js 24.x
        uses: actions/setup-node@v4
        with:
          node-version: 24
          check-latest: true
          cache: npm
      - run: npm ci
      - run: npm run typecheck
        env:
          CI: true
